language: go
go:
  - 1.x
cache:
  directories:
    - $GOPATH/pkg/mod
install:
  - make fetch-tools
  - make vendor
script:
  - make git-validation
  - make fmt
  - make vet
  - make test
  - make lint
